version: '3.7'

services:
    test-mysql:
        container_name: ${CONTAINER_PREFIX}.${ENV}.${MYSQL_CONTAINER_NAME}
        image: mysql
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ${VOLUMNS_PATH}/${CONTAINER_PREFIX}.${ENV}.${MYSQL_CONTAINER_NAME}:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin-trust-function-creators=1
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_SCHEME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always

    test-mongo:
        container_name: ${CONTAINER_PREFIX}.${ENV}.${MONGODB_CONTAINER_NAME}
        image: mongo
        ports:
            - ${MONGODB_PORT}:27017
        volumes:
            - ${VOLUMNS_PATH}/${CONTAINER_PREFIX}.${ENV}.${MONGODB_CONTAINER_NAME}:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
        restart: always
